### ISSUE TITLE
[Bug]: `get_forward_msg`无法获取合并转发内容

### ISSUE THREAD

**Issue by ishkong** [KonataDev/Lagrange.Core#164]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

a576f3708fefe475e8d23c56670cc5d79f064cde

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

使用`get_forward_msg`获取合并转发内容

### 期望的结果是什么？

获取到消息内容

### 实际的结果是什么？

```
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[2]
      [ReverseWSService] Receive: {"action": "get_forward_msg", "params": {"message_id": "*"}, "echo": "16333"}
trce: Lagrange.Core.BotContext[0]
      [2024-03-09 17:40:20] [ServiceContext] [DEBUG]: Outgoing SSOFrame: trpc.group.long_msg_interface.MsgService.SsoRecvLongMsg
trce: Lagrange.Core.BotContext[0]
      [2024-03-09 17:40:20] [ServiceContext] [DEBUG]: Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush
trce: Lagrange.Core.BotContext[0]
      [2024-03-09 17:40:20] [ServiceContext] [DEBUG]: Outgoing SSOFrame: trpc.group.long_msg_interface.MsgService.SsoRecvLongMsg
warn: Lagrange.Core.BotContext[0]
      [2024-03-09 17:40:21] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Message.MultiMsgDownloadEvent
warn: Lagrange.Core.BotContext[0]
      [2024-03-09 17:40:21] [BusinessContext] [WARNING]: Value cannot be null. (Parameter 'buffer')
warn: Lagrange.Core.BotContext[0]
      [2024-03-09 17:40:21] [BusinessContext] [WARNING]:    at System.ArgumentNullException.Throw(String paramName)
         at System.IO.MemoryStream..ctor(Byte[] buffer)
         at Lagrange.Core.Utility.Binary.Compression.GZip.Inflate(Byte[] input) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.Core/Utility/Binary/Compression/GZip.cs:line 9
         at Lagrange.Core.Internal.Service.Message.MultiMsgDownloadService.Parse(Byte[] input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, MultiMsgDownloadEvent& output, List`1& extraEvents) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.Core/Internal/Service/Message/MultiMsgDownloadService.cs:line 45
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Byte[] input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.Core/Internal/Service/BaseService.cs:line 26
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.Core/Internal/Context/ServiceContext.cs:line 103
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.Core/Internal/Context/BusinessContext.cs:line 105
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
         at System.Collections.Generic.List`1.get_Item(Int32 index)
         at Lagrange.OneBot.Core.Operation.Message.GetForwardMsgOperation.HandleOperation(BotContext context, JsonNode payload) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.OneBot/Core/Operation/Message/GetForwardMsgOperation.cs:line 23
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.OneBot/Core/Operation/OperationService.cs:line 55
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"status":"failed","retcode":200,"data":null,"echo":"16333"}
```

**Comment by Linwenxuan05** [comment]
干什么！
<img width="444" alt="image" src="https://github.com/LagrangeDev/Lagrange.Core/assets/116782992/f9adc9f0-4fa5-4d2f-b228-ed1178ca43c1">
message_id是吧.png

**Comment by ishkong** [comment]
```
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[2]
      [ReverseWSService] Receive: {"action": "get_forward_msg", "params": {"id": "X0PrYxe\\u002BkPVS2ERCKAi/kJp2WYZjpcHGcWotvUYcNta11fZ6/XKddXSLDAzkrZZI"}, "echo": "154"}
trce: Lagrange.Core.BotContext[0]
      [2024-03-10 13:17:14] [ServiceContext] [DEBUG]: Outgoing SSOFrame: trpc.group.long_msg_interface.MsgService.SsoRecvLongMsg
warn: Lagrange.Core.BotContext[0]
      [2024-03-10 13:17:15] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Message.MultiMsgDownloadEvent
warn: Lagrange.Core.BotContext[0]
      [2024-03-10 13:17:15] [BusinessContext] [WARNING]: Value cannot be null. (Parameter 'buffer')
warn: Lagrange.Core.BotContext[0]
      [2024-03-10 13:17:15] [BusinessContext] [WARNING]:    at System.ArgumentNullException.Throw(String paramName)
         at System.IO.MemoryStream..ctor(Byte[] buffer)
         at Lagrange.Core.Utility.Binary.Compression.GZip.Inflate(Byte[] input) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.Core/Utility/Binary/Compression/GZip.cs:line 9
         at Lagrange.Core.Internal.Service.Message.MultiMsgDownloadService.Parse(Byte[] input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, MultiMsgDownloadEvent& output, List`1& extraEvents) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.Core/Internal/Service/Message/MultiMsgDownloadService.cs:line 45
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Byte[] input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.Core/Internal/Service/BaseService.cs:line 26
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.Core/Internal/Context/ServiceContext.cs:line 103
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.Core/Internal/Context/BusinessContext.cs:line 105
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
         at System.Collections.Generic.List`1.get_Item(Int32 index)
         at Lagrange.OneBot.Core.Operation.Message.GetForwardMsgOperation.HandleOperation(BotContext context, JsonNode payload) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.OneBot/Core/Operation/Message/GetForwardMsgOperation.cs:line 23
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e) in /home/runner/work/Lagrange.Core/Lagrange.Core/Lagrange.OneBot/Core/Operation/OperationService.cs:line 55
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"status":"failed","retcode":200,"data":null,"echo":"154"}
```
也还是不行（

**Comment by DarkCWK** [comment]
貌似修了?
