### ISSUE TITLE
[Bug?]: Onebot无法发送record消息

### ISSUE THREAD

**Issue by scarletborder** [KonataDev/Lagrange.Core#227]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

329cd8a

### 运行环境

Windows

### 运行架构

x64

### 连接方式

HTTP

### 重现步骤

使用下游应用端http调用lagr.onebot，以下脚本是postman自动生成的
其中user_id非真实id，但是实际上该user_id是机器人的好友
```python
import requests
import json

url = "http://127.0.0.1:8083/send_private_msg"

payload = json.dumps({
  "user_id": 100001,
  "message": [
    {
      "type": "record",
      "data": {
        "file": "https://music.163.com/song/media/outer/url?id=720319.mp3"
      }
    }
  ]
})
headers = {
  'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)
```

### 期望的结果是什么？

{
    "status": "ok",
    "retcode": 200,
    "data": null,
    "echo": null
}

### 实际的结果是什么？

{
    "status": "failed",
    "retcode": 200,
    "data": null,
    "echo": null
}

### 简单的复现代码/链接（可选）

```C#
import requests
import json

url = "http://127.0.0.1:8083/send_private_msg"

payload = json.dumps({
  "user_id": 100001,
  "message": [
    {
      "type": "record",
      "data": {
        "file": "https://music.163.com/song/media/outer/url?id=720319.mp3"
      }
    }
  ]
})
headers = {
  'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)
```

### 日志记录（可选）

```Shell
info: Lagrange.OneBot.Core.Network.Service.HttpService[0]
      Receive(Conn: 4ccb1041-b223-40b8-983e-92bf42384b02: {"action":"send_private_msg","params":{
      "user_id":1000001,
      "message":[
          {
              "type":"record",
              "data":{
                  "file":"https://music.163.com/song/media/outer/url?id=720319.mp3"
              }
          }
      ]
      }})
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
         at System.Range.ThrowArgumentOutOfRangeException()
         at System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray[T](T[] array, Range range)
         at Lagrange.OneBot.Utility.AudioHelper.DetectAudio(Byte[] data, AudioFormat& type) in D:\Code\csharp\Lagrange.Core\Lagrange.OneBot\Utility\AudioHelper.cs:line 27
         at Lagrange.OneBot.Message.Entity.RecordSegment.ConvertFormat(Byte[] audio, Double& audioTime) in D:\Code\csharp\Lagrange.Core\Lagrange.OneBot\Message\Entity\RecordSegment.cs:line 43
         at Lagrange.OneBot.Message.Entity.RecordSegment.Build(MessageBuilder builder, SegmentBase segment) in D:\Code\csharp\Lagrange.Core\Lagrange.OneBot\Message\Entity\RecordSegment.cs:line 27
         at Lagrange.OneBot.Core.Operation.Message.MessageCommon.BuildMessages(MessageBuilder builder, List`1 segments) in D:\Code\csharp\Lagrange.Core\Lagrange.OneBot\Core\Operation\Message\MessageCommon.cs:line 234
         at Lagrange.OneBot.Core.Operation.Message.MessageCommon.ParseChain(OneBotPrivateMessage message) in D:\Code\csharp\Lagrange.Core\Lagrange.OneBot\Core\Operation\Message\MessageCommon.cs:line 115
         at Lagrange.OneBot.Core.Operation.Message.SendPrivateMessageOperation.HandleOperation(BotContext context, JsonNode payload) in D:\Code\csharp\Lagrange.Core\Lagrange.OneBot\Core\Operation\Message\SendPrivateMessageOperation.cs:line 19
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e) in D:\Code\csharp\Lagrange.Core\Lagrange.OneBot\Core\Operation\OperationService.cs:line 58
```

**Comment by scarletborder** [comment]
语音过大导致的
