### ISSUE TITLE
[Bug?]: 在发送较大图片的时候，传base64速度很慢，甚至会断开ws连接

### ISSUE THREAD

**Issue by Special-Week** [KonataDev/Lagrange.Core#228]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

0e95ae8

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

在发送比较大的图片时，发送path速度正常，发送base64时速度很慢，过大的时候甚至断开websocket连接
![cf4be7b6595e7fbae9f3dac4b5463a16](https://github.com/KonataDev/Lagrange.Core/assets/87489040/ad833ff5-4f20-4e4f-98be-8901ed9a0642)
这是发送一张10mb大小的图片，根据显示的时间，发送path用时4s正常用时 但是发送base64的时候花了整整30s.

![ee5dcb917af77ba82e379008e6fff80b](https://github.com/KonataDev/Lagrange.Core/assets/87489040/7667b6de-70b1-4787-8579-b7eac4061351)
这是发送一张15mb大小的图片,显示7s,应该是属于正常用时，但是发送base的时候等了半分多钟，websocket最后断开了
![image](https://github.com/KonataDev/Lagrange.Core/assets/87489040/e37ded09-d69f-4abc-837d-9ae6ac962c38)
这是我用的框架（nonebot2）的部分
![54ece71b358984b7b6ed65919745b373](https://github.com/KonataDev/Lagrange.Core/assets/87489040/c4b1eb93-f704-4834-af07-044b8178b086)
这是lagrange的相关输出

### 期望的结果是什么？

大图片发送base64的时候能拥有和发送path相近的速度

### 实际的结果是什么？

发送时间很长，甚至会断开websocket

### 简单的复现代码/链接（可选）

```C#
from base64 import b64encode
from pathlib import Path

from nonebot import on_command
from nonebot.adapters.onebot.v11 import MessageSegment

test = on_command("test", priority=5, block=True)


@test.handle()
async def _():
    current_path = Path(__file__).parent
    image_path = current_path / "249_DSC0998721_10_22.jpg"
    image_bytes = image_path.read_bytes()
    size = round(len(image_bytes) / 1024 / 1024, 2)
    image_base64 = f"base64://{b64encode(image_bytes).decode()}"

    await test.send(
        MessageSegment.text(f"这是以Path发送{size}MB的图片")
        + MessageSegment.image(image_path)
    )

    await test.send(
        MessageSegment.text(f"这是以base64发送{size}MB的图片")
        + MessageSegment.image(image_base64)
    )

我用的框架是nonebot2，这是在这个框架上用的测试代码
```

### 日志记录（可选）

```Shell
info: Lagrange.Core.BotContext[0]
      [2024-03-21 03:17:58] [MessagingLogic] [VERBOSE]: [MessageChain(288093562)(2516605641)] [Text]: 这是以Path发送15.45MB的图片 | [Image: 0x0] a64ab216390ddaf65b4b39e3da6246c3.jpg 16201367 https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=CgoyNTE2NjA1NjQxEhS0ki19B6FVoDtcvj2DgK-Z4mDryBiX7dwHIP8KKI_Ai5bHg4UDUIC9owE/download?appid=1407&fileid=CgoyNTE2NjA1NjQxEhS0ki19B6FVoDtcvj2DgK-Z4mDryBiX7dwHIP8KKI_Ai5bHg4UDUIC9owE&rkey=CAMSMJm0HgT7wBEcfIaJ3F4-OeeUHsj1tpZeZwrSceAfk6XMXVN3Fgf9nkg-7gD-IG_kmg
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1710962278,"self_id":2516605641,"post_type":"meta_event"}
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1710962283,"self_id":2516605641,"post_type":"meta_event"}
trce: Lagrange.Core.BotContext[0]
      [2024-03-21 03:18:06] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1710962288,"self_id":2516605641,"post_type":"meta_event"}
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1710962293,"self_id":2516605641,"post_type":"meta_event"}
trce: Lagrange.Core.BotContext[0]
      [2024-03-21 03:18:16] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1710962298,"self_id":2516605641,"post_type":"meta_event"}
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1710962303,"self_id":2516605641,"post_type":"meta_event"}
trce: Lagrange.Core.BotContext[0]
      [2024-03-21 03:18:26] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1710962309,"self_id":2516605641,"post_type":"meta_event"}
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1710962314,"self_id":2516605641,"post_type":"meta_event"}
trce: Lagrange.Core.BotContext[0]
      [2024-03-21 03:18:36] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1710962319,"self_id":2516605641,"post_type":"meta_event"}
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1710962324,"self_id":2516605641,"post_type":"meta_event"}
trce: Lagrange.Core.BotContext[0]
      [2024-03-21 03:18:46] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1710962329,"self_id":2516605641,"post_type":"meta_event"}
warn: Lagrange.OneBot.Core.Network.Service.ReverseWSService[3]
      [ReverseWSService] Client disconnected
      System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
       ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
       ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
         at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.IO.Stream.ReadAtLeastAsyncCore(Memory`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsync(Memory`1 buffer, CancellationToken cancellationToken)
         at Lagrange.OneBot.Core.Network.Service.ReverseWSService.ReceiveLoop(ClientWebSocket ws, CancellationToken token)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
         at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SignalCompletion()
         at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SetResult(TResult result)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox.SetResult(TResult result)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.SetResult(TResult result)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.ExecutionContextCallback(Object s)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.MoveNext()
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder.SetResult()
         at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.ExecutionContextCallback(Object s)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.MoveNext()
         at System.IO.Stream.ReadAtLeastAsyncCore(Memory`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream, CancellationToken cancellationToken)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.ExecutionContextCallback(Object s)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.MoveNext()
         at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.ExecutionContextCallback(Object s)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.MoveNext()
         at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__173_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
         at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute()
         at System.Threading.ThreadPoolWorkQueue.Dispatch()
         at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
      --- End of stack trace from previous location ---

         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at System.IO.Stream.ReadAtLeastAsyncCore(Memory`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Lagrange.OneBot.Core.Network.Service.ReverseWSService.ReceiveLoop(ClientWebSocket ws, CancellationToken token)
         at Lagrange.OneBot.Core.Network.Service.ReverseWSService.ExecuteAsync(CancellationToken stoppingToken)
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"sub_type":"connect","meta_event_type":"lifecycle","time":1710962329,"self_id":2516605641,"post_type":"meta_event"}
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1710962329,"self_id":2516605641,"post_type":"meta_event"}
trce: Lagrange.OneBot.Core.Network.S
```

**Comment by DarkCWK** [comment]
只能复现传输 base64 很慢, 很久之后才成功
无法复现断开的情况, 疑似框架问题

**Comment by DarkCWK** [comment]
目前可行的方案为屏蔽其日志

```jsonc
// appsettings.json
{
    "Logging": {
        "LogLevel": {
            // ......
            // 反向 WS
            "Lagrange.OneBot.Core.Network.Service.ReverseWSService":"Debug",
            // 正向 WS
            "Lagrange.OneBot.Core.Network.Service.ForwardWSService":"Debug",
            // Http, 其使用 Information 级别打印接受的数据
            "Lagrange.OneBot.Core.Network.Service.HttpService":"Warning"
        }
    },
    // ......
}
```

**Comment by PhotonSPK** [comment]
Try #231

**Comment by Special-Week** [comment]
新的(action)[https://github.com/KonataDev/Lagrange.Core/actions/runs/8370029903]
尝试过了, 情况改善不少，但感觉依旧不是很理想，不知道开发者们怎么看
![2d3124540135808b3ea0b9c3a2cc41c9](https://github.com/KonataDev/Lagrange.Core/assets/87489040/9147b263-5500-431f-9470-6a4a672ecebe)
然后这边是我切换gocqhttp的用时
![3d1f7c7013da7dc8127632f694215e63](https://github.com/KonataDev/Lagrange.Core/assets/87489040/4120b26f-e370-4901-a677-e20239b839fc)

**Comment by Linwenxuan05** [comment]
大概是因为连接到Sign服务器需要300ms-500ms的时间

Special-Week ***@***.***> 于2024年3月21日周四 14:20写道：
