### ISSUE TITLE
[Bug]: 踢出 Bot 自身时会产生 Warn 日志

### ISSUE THREAD

**Issue by Director259** [KonataDev/Lagrange.Core#255]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

db45b79

### 运行环境

Windows

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

Received message {"sub_type":"3","group_id":347831900,"operator_id":0,"uiser_id":281551284,"notice_type":"group_decrease","time":1711779685,"self_id":2816551284,"post_type":"notice"}

### 期望的结果是什么？

能够抓取到具体的operator_id

### 实际的结果是什么？

未能抓取到实际对象

**Comment by DarkCWK** [comment]
bot 是管理员吗？目前只有管理员才能获取到 `operator_id`

**Comment by Director259** [comment]
> bot 是管理员吗？目前只有管理员才能获取到 `operator_id`

确实不是，在加上管理后试了一下，终端报错了
info: Lagrange.Core.BotContext[0]
      [2024-03-30 18:45:11] [CachingLogic] [VERBOSE]: Caching group members: 242150793
warn: Lagrange.Core.BotContext[0]
      [2024-03-30 18:45:12] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.System.FetchMembersEvent
warn: Lagrange.Core.BotContext[0]
      [2024-03-30 18:45:12] [BusinessContext] [WARNING]: Value cannot be null. (Parameter 'source')
warn: Lagrange.Core.BotContext[0]
      [2024-03-30 18:45:12] [BusinessContext] [WARNING]:    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
         at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
         at Lagrange.Core.Internal.Service.System.FetchMembersService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, FetchMembersEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
info: Lagrange.OneBot.Core.Notify.NotifyService[0]
      [18:45:12] GroupMemberDecreaseEvent: 242150793 | 2816551284 | 0 | 3
![8F239XNLUSU_8R2KQ8GGAR8](https://github.com/KonataDev/Lagrange.Core/assets/127825341/96b48344-3f04-470d-90ac-74190c26bf23)
不确定是不是稳定复现因为我目前只有一个号能搞拉格兰测试

**Comment by DarkCWK** [comment]
希望能详细说说具体的离开流程
是被踢的？还是自行离开的？
目前我无法复现

**Comment by Director259** [comment]
> 希望能详细说说具体的离开流程 是被踢的？还是自行离开的？ 目前我无法复现

触发时候是被我手动踢出，在这之前是先给了一个管理，然后我群主身份将作为管理的bot移出

**Comment by DarkCWK** [comment]
> 触发时候是被我手动踢出，在这之前是先给了一个管理，然后我群主身份将作为管理的bot移出

仍旧无法复现，有没有其他没有注意到的细节？

**Comment by Director259** [comment]
> > 触发时候是被我手动踢出，在这之前是先给了一个管理，然后我群主身份将作为管理的bot移出
> 
> 仍旧无法复现，有没有其他没有注意到的细节？

除了是管理以外应该没有了，我拿另一个群试了一下也是类似的报错，其他ntqq相关的权限细节我不太清楚，不过我用来移出bot的账号（群主账号）还没有在任意ntqq框架上登陆过，是否有这方面的影响？
info: Lagrange.Core.BotContext[0]
      [2024-03-30 19:15:33] [CachingLogic] [VERBOSE]: Caching group members: 732231697
warn: Lagrange.Core.BotContext[0]
      [2024-03-30 19:15:33] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.System.FetchMembersEvent
warn: Lagrange.Core.BotContext[0]
      [2024-03-30 19:15:33] [BusinessContext] [WARNING]: Value cannot be null. (Parameter 'source')
warn: Lagrange.Core.BotContext[0]
      [2024-03-30 19:15:33] [BusinessContext] [WARNING]:    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
         at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
         at Lagrange.Core.Internal.Service.System.FetchMembersService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, FetchMembersEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
info: Lagrange.OneBot.Core.Notify.NotifyService[0]
      [19:15:33] GroupMemberDecreaseEvent: 732231697 | 2816551284 | 0 | 3
![)TX5ZXUR8V`95X{PBU6RWYX](https://github.com/KonataDev/Lagrange.Core/assets/127825341/b6478b76-d794-41e0-ae1e-911905994bc1)

**Comment by DarkCWK** [comment]
已经成功复现
