### ISSUE TITLE
[Bug]: 私聊下Bot自己发送的消息的`message_id`，无法用于`/get_msg`或`/delete_msg`

### ISSUE THREAD

**Issue by snowykami** [KonataDev/Lagrange.Core#260]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

db45b79

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

```python
msg_id = (await bot.send_private_msg(
    message="test",
    user_id=机器人自身的id
))["message_id"]
# 到这里可以正常获取到message_id
# 然后
await bot.get_msg(message_id=msg_id)
await bot.delete_msg(message_id=msg_id)
# 以上两个api均会报错，且仅在私聊发生
```

### 期望的结果是什么？

`/get_msg`和`/delete_msg`请求成功后的回应

### 实际的结果是什么？

Lagrange.OneBot控制台输出：
```log
info: Lagrange.Core.BotContext[0]
      [2024-03-31 00:02:30] [MessagingLogic] [VERBOSE]: [MessageChain(发送者ID)] [Text]: test
info: Lagrange.Core.BotContext[0]
      [2024-03-31 00:02:32] [MessagingLogic] [VERBOSE]: [MessageChain(机器人ID)] [Image: 1920x1248] 9e7898be78b474781abccf65d750c449.png 70472 https://multimedia.nt.qq.com.cn/download?appid=1406&fileid=CgoyNDQzNDI5MjA0EhQYKnj4I18JrXMrKhgL9CdpW8ysDBjIpgQg_goolYSVkq6chQM&rkey=CAQSMHT2KuVv2HrCc18aRCTRjoK2pMo_KSSVO5z4VFKAn1rqvsLDy6JD97mrB4Hd78TJOQ&spec=0
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Lagrange.OneBot.Database.MessageRecord.op_Explicit(MessageRecord record)
         at Lagrange.OneBot.Core.Operation.Message.DeleteMessageOperation.HandleOperation(BotContext context, JsonNode payload)
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e)
```

Nonebot这边显示
```log
2024-03-30 23:33:30 [⭕出错辣] <nonebot.message._run_matcher:430> Running Matcher(type='message', module=liteyuki.liteyuki_main.webdash, lineno=18) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Program Files\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Program Files\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Program Files\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\snowy\Projects\LiteyukiBot6\liteyuki\liteyuki_main\reloader.py", line 32, in _run
    _nb_run(*args, **kwargs)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\snowy\Projects\LiteyukiBot6\liteyuki\liteyuki_main\webdash.py", line 71, in _
    await md.get_image_url(open("data/output.png", "rb").read(), bot)
  File "D:\snowy\Projects\LiteyukiBot6\liteyuki\utils\message.py", line 138, in get_image_url
    await bot.delete_msg(message_id=image_message_id)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=200, data=None, echo='2')
```

### 简单的复现代码/链接（可选）

```C#
@staticmethod
    async def get_image_url(image: bytes | str, bot: T_Bot) -> str:
        """把图片上传到图床，返回链接
        Args:
            bot: 发送的bot
            image: 图片字节流或图片本地路径
        Returns:
        """
        if isinstance(image, str):
            image = open(image, "rb")
        elif isinstance(image, bytes):
            image = io.BytesIO(image)
        else:
            raise ValueError("image type not supported")
        image_message_id = (await bot.send_private_msg(
            user_id=bot.self_id,
            message=v11.Message(
                v11.MessageSegment.image(
                    file=image
                )
            )
        ))["message_id"]
        print(image_message_id, type(image_message_id))
        await asyncio.sleep(5)
        await bot.delete_msg(message_id=image_message_id)
```

### 日志记录（可选）

```Shell
info: Lagrange.Core.BotContext[0]
      [2024-03-31 00:02:30] [MessagingLogic] [VERBOSE]: [MessageChain(发送者ID)] [Text]: test
info: Lagrange.Core.BotContext[0]
      [2024-03-31 00:02:32] [MessagingLogic] [VERBOSE]: [MessageChain(机器人ID)] [Image: 1920x1248] 9e7898be78b474781abccf65d750c449.png 70472 https://multimedia.nt.qq.com.cn/download?appid=1406&fileid=CgoyNDQzNDI5MjA0EhQYKnj4I18JrXMrKhgL9CdpW8ysDBjIpgQg_goolYSVkq6chQM&rkey=CAQSMHT2KuVv2HrCc18aRCTRjoK2pMo_KSSVO5z4VFKAn1rqvsLDy6JD97mrB4Hd78TJOQ&spec=0
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Lagrange.OneBot.Database.MessageRecord.op_Explicit(MessageRecord record)
         at Lagrange.OneBot.Core.Operation.Message.DeleteMessageOperation.HandleOperation(BotContext context, JsonNode payload)
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e)
```

### 补充说明（可选）

在之前的[issue #219 ](https://github.com/KonataDev/Lagrange.Core/issues/219)里面看到了类似的内容，那边说法是Bot不应该获取到自身的消息，但是在某些私聊场景中`/delete_msg`撤回机器人自身消息也是有使用需求的。

**Comment by Linwenxuan05** [comment]
因为数据库没入库 今晚回去修

**Comment by snowykami** [comment]
使用commit:[44477b9](https://github.com/KonataDev/Lagrange.Core/commit/44477b9ee9ee1c7de6d34b223fc6035ce0314704)
按照上述步骤获取`message_id`后，调用`/get_msg`目前可以正常响应，但是返回的图片消息必要字段有缺失，例如`url`
```python
{'time': -2147483648, 'message_type': 'private', 'message_id': 9512791, 'real_id': 9512791, 'sender': {'user_id': 0, 'nickname': '', 'sex': 'unknown'}, 'message': [{'type': 'image', 'data': {'file': None, 'url': None}}]}
```

调用`/delete_msg`后仍然`ActionFailed`，Nonebot2日志
```
2024-04-01 21:02:04 [*️⃣调试] <nonebot.utils.log:323> OneBot V11 | Calling API delete_msg
2024-04-01 21:02:04 [⭕错误] <nonebot.bot.call_api:90> Error when running CallingAPI hook. Running cancelled!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Program Files\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Program Files\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Program Files\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\snowy\Projects\LiteyukiBot6\liteyuki\liteyuki_main\reloader.py", line 32, in _run
    _nb_run(*args, **kwargs)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\snowy\Projects\LiteyukiBot6\liteyuki\liteyuki_main\runtime.py", line 133, in _
    await stats.finish(MessageSegment.image(image_bytes))
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 574, in finish
    await cls.send(message, **kwargs)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 558, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 228, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 181, in send
    return await bot.send_msg(**params)
> File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 82, in call_api
    await asyncio.gather(*coros)
  File "D:\snowy\Projects\LiteyukiBot6\liteyuki\liteyuki_main\core.py", line 178, in test_for_md_image
    result = await md.send_image(file_bytes, bot, message_type=session_type, session_id=session_id)
  File "D:\snowy\Projects\LiteyukiBot6\liteyuki\utils\message.py", line 134, in send_image
    await bot.delete_msg(message_id=image_message_id)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "D:\snowy\Projects\LiteyukiBot6\.venv\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=200, data=None, echo='7')
```

Lagrange.OneBot日志，我关闭了`IgnoerSelf`，可以看到Bot接收了自身消息，并且此消息的图片url可以正常使用，但是为什么get_msg返回的值是None呢
```
info: Lagrange.Core.BotContext[0]
      [2024-04-01 21:08:35] [MessagingLogic] [VERBOSE]: [MessageChain(2751454815)] [Text]: stats
info: Lagrange.Core.BotContext[0]
      [2024-04-01 21:08:52] [MessagingLogic] [VERBOSE]: [MessageChain(2443429204)] [Image: 2000x1532] c692d50a42c690c698c655450b46375a.png 2394044 https://multimedia.nt.qq.com.cn/download?appid=1406&fileid=CgoyNDQzNDI5MjA0EhRSSfwyV7-9Mv5U_z_JEsy5mk5eUBi8j5IBIP4KKNvfwYWLoYUD&rkey=CAMSMA6DHuM4Inf6M-l5W0jDlBw70kKea5y-Q0YhSt2KPgjAUZH6h8zWLDkppKdXOwHLVQ&spec=0
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.Exception: Exception of type 'System.Exception' was thrown.
         at Lagrange.OneBot.Core.Operation.Message.DeleteMessageOperation.HandleOperation(BotContext context, JsonNode payload)
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e)
```

**Comment by DarkCWK** [comment]
目前可以使用，但获取bot发送的私聊消息时 sender 为对方的id
目测是使用的发送时构造的 chain，其中的 FriendUin 为对方的 uin，所以入库时存储的是对方的信息
