### ISSUE TITLE
[Bug?]: 合并转发图片消息时报错

### ISSUE THREAD

**Issue by mirai-MIC** [KonataDev/Lagrange.Core#269]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

6d65566

### 运行环境

Linux

### 运行架构

x86

### 连接方式

正向 WebSocket

### 重现步骤

1.选择合并转发一张或多张图片

### 期望的结果是什么？

图片应该被成功合并转发。

### 实际的结果是什么？

机器人出现错误，无法合并转发图片

### 简单的复现代码/链接（可选）

```C#
{
    "messages": [
        {
            "type": "node",
            "data": {
                "name": "昵称",
                "uin": "3092179918",
                "content": [
                    {
                        "type": "image",
                        "data": {
                            "file": "https://img.likepoems.com/resource/mc/i3i38kRus31TeaOfO37h.jpg"
                        }
                    }
                ]
            }
        }
    ]
}
```

### 日志记录（可选）

```Shell
warn: Lagrange.Core.BotContext[0]
      [2024-04-01 12:13:48] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.System.FetchMembersEvent
warn: Lagrange.Core.BotContext[0]
      [2024-04-01 12:13:48] [BusinessContext] [WARNING]: Value cannot be null. (Parameter 'source')
warn: Lagrange.Core.BotContext[0]
      [2024-04-01 12:13:48] [BusinessContext] [WARNING]:    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
         at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
         at Lagrange.Core.Internal.Service.System.FetchMembersService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, FetchMembersEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
warn: Lagrange.Core.BotContext[0]
      [2024-04-01 12:13:48] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Message.ImageGroupUploadEvent
warn: Lagrange.Core.BotContext[0]
      [2024-04-01 12:13:48] [BusinessContext] [WARNING]: Object reference not set to an instance of an object.
warn: Lagrange.Core.BotContext[0]
      [2024-04-01 12:13:48] [BusinessContext] [WARNING]:    at Lagrange.Core.Internal.Service.Message.ImageGroupUploadService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ImageGroupUploadEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
fail: Lagrange.Core.BotContext[0]
      [2024-04-01 12:13:48] [HighwayContext] [FATAL]: Upload resources for ImageEntity failed
warn: Lagrange.Core.BotContext[0]
      [2024-04-01 12:15:57] [BusinessContext] [WARNING]: Object reference not set to an instance of an object.
warn: Lagrange.Core.BotContext[0]
      [2024-04-01 12:15:57] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Message.ImageGroupUploadEvent
warn: Lagrange.Core.BotContext[0]
      [2024-04-01 12:15:57] [BusinessContext] [WARNING]:    at Lagrange.Core.Internal.Service.Message.ImageGroupUploadService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ImageGroupUploadEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
fail: Lagrange.Core.BotContext[0]
      [2024-04-01 12:15:57] [HighwayContext] [FATAL]: Upload resources for ImageEntity failed
```
```


### 补充说明（可选）

其他信息:
使用的docker打包镜像
构造转发其他内容消息(text消息)和单独发image消息都没问题

**Comment by deeplycoffee** [comment]
报错解决了吗?这个问题也困扰了我几天了,怎么都找不到答案...

**Comment by deeplycoffee** [comment]
> > 报错解决了吗?这个问题也困扰了我几天了,怎么都找不到答案...
> 
> /send_forward_msg
> 
> ```
> {
>     "messages": [
>         {
>             "type": "node",
>             "data": {
>                 "name": "昵称",
>                 "uin": "123454678",
>                 "content": [
>                     {
>                         "type": "text",
>                         "data": {
>                             "text": "f**k forward!"
>                         }
>                     }
>                 ]
>             }
>         },
>         {
>             "type": "node",
>             "data": {
>                 "name": "昵称",
>                 "uin": "123456789",
>                 "content": [
>                     {
>                         "type": "image",
>                         "data": {
>                             "file": "https://iw233.cn/api.php?sort=random"
>                         }
>                     }
>                 ]
>             }
>         }
>     ]
> }
> ```
> 
> 应该没啥问题了，但是图片还是一如既往的不显示

嘿我找到解决方案了...刚刚翻阅后面的issue找到了可能的原因,大意如下:
> `send_forward_msg` 拿到的似乎是私聊的密钥, 使用`send_group_forward_msg`就能解决这个问题了

**Comment by deeplycoffee** [comment]
怎么我第一天查issue就没找到这个解答呢hh
