### ISSUE TITLE
[Bug?]: get_cookies 报错

### ISSUE THREAD

**Issue by Louisover** [KonataDev/Lagrange.Core#309]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

61ee20a

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

调用 onebot 的 get_cookies 就会报错

### 期望的结果是什么？

获取到 cookies

### 实际的结果是什么？

报错

### 日志记录（可选）

```Shell
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[2]
      [ReverseWSService] Receive: {"action": "get_msg", "params": {"message_id": 1915032867}, "echo": "1"}
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"status":"ok","retcode":0,"data":{"time":1712900888,"message_type":"group","message_id":1915032867,"real_id":1915032867,"sender":{"user_id":******,"nickname":"******","sex":"unknown"},"message":[{"type":"text","data":{"text":"\u6D4B\u8BD5"}}]},"echo":"1"}
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[2]
      [ReverseWSService] Receive: {"action": "get_cookies", "params": {"domain": "qq.com"}, "echo": "2"}
trce: Lagrange.Core.BotContext[0]
      [2024-04-12 13:48:12] [ServiceContext] [DEBUG]: Outgoing SSOFrame: OidbSvcTrpcTcp.0x102a_0
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
         at System.Collections.Generic.List`1.get_Item(Int32 index)
         at Lagrange.OneBot.Core.Operation.Generic.GetCookiesOperation.HandleOperation(BotContext context, JsonNode payload)
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e)
warn: Lagrange.Core.BotContext[0]
      [2024-04-12 13:48:12] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.System.FetchCookieEvent
warn: Lagrange.Core.BotContext[0]
      [2024-04-12 13:48:12] [BusinessContext] [WARNING]: Value cannot be null. (Parameter 'source')
warn: Lagrange.Core.BotContext[0]
      [2024-04-12 13:48:12] [BusinessContext] [WARNING]:    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
         at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
         at Lagrange.Core.Internal.Service.System.FetchCookieService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, FetchCookieEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Service.BaseService`1.Lagrange.Core.Internal.Service.IService.Parse(Span`1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents)
         at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
      [ReverseWSService] Send: {"status":"failed","retcode":200,"data":null,"echo":"2"}
trce: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1]
```

**Comment by CrackTC** [comment]
好像只能获取`qun.qq.com`和`vip.qq.com`的cookies
