### ISSUE TITLE
[Bug?]: 使用Send_msg无法引用其他信息并回复

### ISSUE THREAD

**Issue by DanielToyama** [KonataDev/Lagrange.Core#311]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

[Core][Onebot] Add Summary field to ImageEntity class. (#307)

### 运行环境

Windows

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

使用bot发送
```js
{
  "action": "send_msg",
  "echo": "01212345678123456789a12123456789ab123456789abcde1234-1234567112345678-41123123456789abcde-123456789a123456789abc1234567891234567-12341234567812123456789a123456789abc12311123456123456789abcd",
  "params": {
    "message": [
      {
        "type": "reply",
        "data": {
          "id": 286230276
        }
      },
      {
        "type": "text",
        "data": {
          "text": "已上线"
        }
      }
    ],
    "message_type": "group",
    "group_id":12345
  }
}
```

### 期望的结果是什么？

正常发信息“已上线”并且引用发信人信息

### 实际的结果是什么？

无法发出
```
{
  status: 'failed',
  retcode: 200,
  data: null,
  echo: '01212345678123456789a12123456789ab123456789abcde1234-1234567112345678-41123123456789abcde-123456789a123456789abc1234567891234567-12341234567812123456789a123456789abc12311123456123456789abcd'
}
```

### 日志记录（可选）

```Shell
Lagrange.Core.BotContext[0]
      [2024-04-13 01:37:01] [MessagingLogic] [VERBOSE]: [MessageChain(741152727)(2370408621)] [Text]: bot测试
trce: Lagrange.OneBot.Core.Network.Service.ForwardWSService[12]
      Receive(1d81aa08-b233-42e7-9320-fd4965f9af8b) {"action":"send_msg","echo":"123456789abcd012345123456789abcd0123456789a12345-1234567812345670123-4123451234561234-1234567123412-123456789abc1234567890121123456789abcd123456789123456789abcde123456789abcd12345670","params":{"message":[{"type":"reply","data":{"id":286283775}},{"type":"text","data":{"text":"已上线"}}],"message_type":"group","group_id":741152727}}
warn: Lagrange.OneBot.Core.Operation.OperationService[0]
      Unexpected error encountered while handling message.
      System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.id | LineNumber: 0 | BytePositionInLine: 15.
       ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
         at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedString(JsonTokenType tokenType)
         at System.Text.Json.Utf8JsonReader.GetString()
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
         at System.Text.Json.JsonSerializer.Deserialize(JsonElement element, Type returnType, JsonSerializerOptions options)
         at Lagrange.OneBot.Core.Operation.Message.MessageCommon.BuildMessages(MessageBuilder builder, List`1 segments)
         at Lagrange.OneBot.Core.Operation.Message.MessageCommon.ParseChain(OneBotMessage message)
         at Lagrange.OneBot.Core.Operation.Message.SendMessageOperation.HandleOperation(BotContext context, JsonNode payload)
         at Lagrange.OneBot.Core.Operation.OperationService.HandleOperation(MsgRecvEventArgs e)
trce: Lagrange.OneBot.Core.Network.Service.ForwardWSService[13]
      Send(1d81aa08-b233-42e7-9320-fd4965f9af8b) {"status":"failed","retcode":200,"data":null,"echo":"123456789abcd012345123456789abcd0123456789a12345-1234567812345670123-4123451234561234-1234567123412-123456789abc1234567890121123456789abcd123456789123456789abcde123456789abcd12345670"}
```

**Comment by CrackTC** [comment]
reply的id需要为string类型

**Comment by DanielToyama** [comment]
好吧，虽然gocq这样可以发（）
