### ISSUE TITLE
[Bug?]: 处理"邀请进群“事件时出现后台刷屏报错

### ISSUE THREAD

**Issue by Aliorpse** [KonataDev/Lagrange.Core#349]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

9435fb4

### 运行环境

Windows

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

邀请bot进群

### 期望的结果是什么？

正常收到事件

### 实际的结果是什么？

后台出现刷屏报错，日志见下

### 日志记录（可选）

```Shell
warn: Lagrange.Core.BotContext[0]

[2024-05-02 18:11:52] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.System.FetchUserInfoEvent

warn: Lagrange.Core.BotContext[0]

[2024-05-02 18:11:52] [BusinessContext] [WARNING]: Year, Month, and Day parameters describe an un-representable DateTime.

warn: Lagrange.Core.BotContext[0]

[2024-05-02 18:11:52] [BusinessContext] [WARNING]:    at Lagrange.Core.Internal.Service.System.FetchUserInfoService.Parse(Span1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, FetchUserInfoEvent&amp; output, List1& extraEvents)

at Lagrange.Core.Internal.Service.BaseService1.Lagrange.Core.Internal.Service.IService.Parse(Span1 input, BotKeystore keystore, BotAppInfo appInfo, BotDeviceInfo device, ProtocolEvent& output, List`1& extraEvents)

at Lagrange.Core.Internal.Context.ServiceContext.ResolveEventByPacket(SsoPacket packet)

at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event)
```

### 补充说明（可选）

使用trssyunzai对接，找到过类似的issue，但似乎没有给出详细的问题记录

**Comment by RexQian** [comment]
同样遇到了这个问题 获取用户的生日信息报错了
无能力修复 写死生日 可以避免这个问题
<img width="902" alt="image" src="https://github.com/LagrangeDev/Lagrange.Core/assets/1394070/4fdf84db-a159-4ed5-bd5b-b7ec01ff9494">

**Comment by RexQian** [comment]
从日志上可能取到的生日是0 0 0 所以修正的方法是当生日无效的时候 设置为空或者1970-01-01这样的魔法值来解决这个问题
